# Auto-generated from the 3 Excel manpower files.
# Counts: staff=96 worker=156 resource=102

STAFF_SEED = [
    ("Administration Department", "Administration Manager"),
    ("Administration Department", "Admin/HR officer"),
    ("Administration Department", "Admin/HR Assistant"),
    ("Administration Department", "PRO/Sr. PRO"),
    ("Accounts Department", "Finance Manager"),
    ("Accounts Department", "Accountant Senior"),
    ("Accounts Department", "Accountant"),
    ("M.E.P. Department", "MEP Director/Manager"),
    ("M.E.P. Department", "MEP Project Manager"),
    ("M.E.P. Department", "MEP Coordinator / Engineer."),
    ("M.E.P. Department", "Eng. Mechanical /Senior / Jr."),
    ("M.E.P. Department", "Electrical Engineer/Senior/Assist."),
    ("M.E.P. Department", "Supervisor Mechanical / Mep"),
    ("M.E.P. Department", "Draughtsman Electrical"),
    ("M.E.P. Department", "Draughtsman MEP +Mechanical"),
    ("Contracts & Purchase Department", "Commercial Director"),
    ("Contracts & Purchase Department", "Contracts Director"),
    ("Contracts & Purchase Department", "Contracts Administrator"),
    ("Contracts & Purchase Department", "Close out / DLP manager"),
    ("Contracts & Purchase Department", "Manager Cost Control"),
    ("Contracts & Purchase Department", "Purchase Officer/Procurement/Manager/Eng."),
    ("QA/QC Department", "QA/QC Director/ Manager / Sr."),
    ("QA/QC Department", "QA/QC Engineer/MEP/Sr./Jr."),
    ("QA/QC Department", "QA/QC Lab. Incharge"),
    ("QA/QC Department", "QA/QC Inspector/Asst./Jr."),
    ("QA/QC Department", "Lab. Technician/Engineer"),
    ("Precast / Batching Department", "Batching Plant Manager"),
    ("Precast / Batching Department", "Production Manager"),
    ("Precast / Batching Department", "Precast Div. Director"),
    ("Precast / Batching Department", "Inventory Officer/Technician Machine"),
    ("Precast / Batching Department", "Clearing Agent/Alignment Foreman"),
    ("HSE Department (Safety)", "HSE/CampManager"),
    ("HSE Department (Safety)", "HSE Manager"),
    ("HSE Department (Safety)", "HSE Advisor/Sr./Officer/Engineer"),
    ("HSE Department (Safety)", "HSE Inspector + Assistants"),
    ("HSE Department (Safety)", "Lifting Supervisor"),
    ("HSE Department (Safety)", "Male Nurse/First Aider"),
    ("Technical Department", "Technical Director"),
    ("Technical Department", "Technical Manager / MEP"),
    ("Technical Department", "Structural Engineer / Sr."),
    ("Technical Department", "Architect Senior"),
    ("Technical Department", "Architect"),
    ("Technical Department", "Design Manager Fit Out Sr"),
    ("Technical Department", "Technical Engineer / Project/Coordinator"),
    ("Technical Department", "Material Engineer"),
    ("Technical Department", "Draughtsman/woman Civil + Arch. + Sr.+Surveyor+Technical"),
    ("Technical Department", "Estimator"),
    ("Technical Department", "QS Civil + MEP + Junior + Senior"),
    ("Engineering Department", "Chief Operating Officer"),
    ("Engineering Department", "Production Manager"),
    ("Engineering Department", "Project/s Director"),
    ("Engineering Department", "Planning Manager / Precast"),
    ("Engineering Department", "Planning Engineer / Senior / Junior"),
    ("Engineering Department", "Project Manager/Senior/Precast"),
    ("Engineering Department", "Construction Manager/Senior"),
    ("Engineering Department", "Project Engineer/Senior"),
    ("Engineering Department", "Engineer Finishing"),
    ("Engineering Department", "Site Engineer / Civil Eng. + Asstt."),
    ("1", "I.T. Engineer"),
    ("1", "I.T. Technician/I.T & Logistic"),
    ("1", "Landscaping Manager"),
    ("1", "DLP Coordinator"),
    ("1", "Precast Division Director"),
    ("1", "Receptionist / Secretary/Customer Service Rep."),
    ("1", "Document Controllers / Sr. + Asstt."),
    ("1", "Data Entry"),
    ("1", "Sales / Purchase / Administrator /Archivist (Local)"),
    ("1", "General Foreman/Supervisor"),
    ("1", "Manager Water proof Section"),
    ("1", "Time Keeper + Assistant"),
    ("Joinery Department", "Operations Director"),
    ("Joinery Department", "Technical / Manager Fit Out / Engineer"),
    ("Joinery Department", "Architect / Architect Sr."),
    ("Joinery Department", "Draughtsman joinery/Architectural"),
    ("Joinery Department", "Factory Manager"),
    ("Joinery Department", "Safety Inspector"),
    ("Joinery Department", "Office boy"),
    ("Joinery Department", "Project Coordinator/ QA/QC Inspector"),
    ("Joinery Department", "Store Keeper / Assistant / Helper/ Time Keeper"),
    ("Joinery Department", "QA/QC /Engineer / Inspector / Q.S"),
    ("Joinery Department", "Project Engineer  / Accountant Jr."),
    ("Aluminium Department", "Operations Manager"),
    ("Aluminium Department", "Draughtsman Aluminium/Senior/Junior/CNC"),
    ("Aluminium Department", "Designer Façade/Designer Eng /Designer Team leader"),
    ("Aluminium Department", "Engineer Structural"),
    ("Aluminium Department", "Estimator Senior"),
    ("Aluminium Department", "Factory Incharge/Coordinator"),
    ("Aluminium Department", "Office boy"),
    ("Aluminium Department", "Project Coordinator/Q.S"),
    ("Aluminium Department", "Project Manager / Technical Manager / Engineer Site/Civil"),
    ("Aluminium Department", "PRO/Sales/Admin supervisor (Local)"),
    ("Aluminium Department", "Purchase Officer / Data Entry"),
    ("Aluminium Department", "Site Steel Manager"),
    ("Aluminium Department", "Material Engineer"),
    ("Aluminium Department", "Store Keeper /Assistant / Helper"),
    ("Aluminium Department", "Time Keeper"),
]
# STAFF_SEED: 96 entries

WORKER_SEED = [
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Foreman A/C  /  Mechanical Foreman"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Chargehand A/C"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "A/C Technician"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Charge Hand A/C / Ducting"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Duct Installer / Fabricator / Insulator"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Foreman Electrical"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Chargehand Electrician / MEP"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Electrician/Assistant"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Plumber Charge hand"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Foreman Plumbing"),
    ("M.E.P. Department      (Mr. Sinan Jaleel, MEP Manager)", "Plumber"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Foreman GRC"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Charge Hand GRC"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Foreman Gypsum"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Charge Hand Gypsum"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Foreman Finishing Carp."),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Finishing Charge Hand"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "GRC workers"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Gypsum Fixer / Fitter"),
    ("Gypsum / GRC Department      (Mr. Mamoun al Toramzavi)", "Carpenter Finishing"),
    ("Land Surveying Department     (Saim Bashir, Chief Surveyor)", "Chief Land Surveyor"),
    ("Land Surveying Department     (Saim Bashir, Chief Surveyor)", "Land Surveyor / Sr."),
    ("Land Surveying Department     (Saim Bashir, Chief Surveyor)", "Land Surveyor Assistant"),
    ("Land Surveying Department     (Saim Bashir, Chief Surveyor)", "Chain Man"),
    ("Water proofing Department", "Foreman Water Proofing/Charge Hand"),
    ("Water proofing Department", "Mason Water Proofing"),
    ("Stores Department", "Stores In Charge"),
    ("Stores Department", "Store Keepers/Store Supervisor"),
    ("Stores Department", "Store Keepers Assistant"),
    ("Stores Department", "Sand Blaster"),
    ("Drivers and Operators", "Driver Heavy bus (80 seater busses)"),
    ("Drivers and Operators", "Driver LD (Mini Bus, 3ton P/up,etc.)"),
    ("Drivers and Operators", "Driver HD (Trailers,Six wheel, Tanker)"),
    ("4", "Operator HD + Bobcat + M.Crane+Forlift"),
    ("4", "Pump Operator + Asstt."),
    ("4", "Tower Crane Operator/Rigger"),
    ("Plant Dept. / Repairing workshop", "Plant Manager / Coord/Works Mang/Transp. Superv."),
    ("Plant Dept. / Repairing workshop", "Purchaser Spare parts"),
    ("Plant Dept. / Repairing workshop", "Logistic /Manager/ Foreman / Ch. Hands/Supervisor/Asst."),
    ("Plant Dept. / Repairing workshop", "Foreman Auto Electrician"),
    ("Plant Dept. / Repairing workshop", "Auto Electrician"),
    ("Plant Dept. / Repairing workshop", "Auto Denter Spray Painter"),
    ("Plant Dept. / Repairing workshop", "Electrical Tools Mechanic"),
    ("Plant Dept. / Repairing workshop", "Foreman Mechanic"),
    ("Plant Dept. / Repairing workshop", "Mechanic/Asst./Maintenance"),
    ("Plant Dept. / Repairing workshop", "Mechanic Tower Crane"),
    ("Plant Dept. / Repairing workshop", "Foreman Maintenance"),
    ("Plant Dept. / Repairing workshop", "Puncturer / Tyreman"),
    ("Plant Dept. / Repairing workshop", "Tanker Helper"),
    ("Plant Dept. / Repairing workshop", "Welder"),
    ("Office Boy - Security - Camps attendant", "Office Boy/ office assistant"),
    ("Office Boy - Security - Camps attendant", "Camps Incharge/Manager"),
    ("Office Boy - Security - Camps attendant", "Camp Boss/Assistant"),
    ("Office Boy - Security - Camps attendant", "Watchman / Security"),
    ("Precast Department", "Foreman /Fabric/Production/ Stockyard/ coordin."),
    ("Precast Department", "Charge Hand Production Precast"),
    ("Precast Department", "Supervisor Maintenance"),
    ("Precast Department", "Dispatch Worker"),
    ("Precast Department", "Foreman Erector"),
    ("Precast Department", "Erector Precast"),
    ("Precast Department", "Carpenter Precast"),
    ("Masonry Dept.", "Foreman Civil"),
    ("Masonry Dept.", "Foreman Mason, BP/"),
    ("Masonry Dept.", "Ch. H. Mason BP & Civil"),
    ("Masonry Dept.", "Mason Block Plaster"),
    ("Masonry Dept.", "Foreman Mason Tile"),
    ("Masonry Dept.", "Charge Hand Mason Tile"),
    ("Masonry Dept.", "Mason Tile + Asstt."),
    ("Painting Dept.", "Foreman Painter"),
    ("Painting Dept.", "Charge hand Painter"),
    ("Painting Dept.", "Painter Building"),
    ("Scaffolding Dept.", "Foreman Scaffolder / Supervisor"),
    ("Scaffolding Dept.", "Chargehand Scaffolder"),
    ("Scaffolding Dept.", "Scaffolder"),
    ("Carpentry Dept.", "Foreman Carpenter"),
    ("Carpentry Dept.", "Charge Hand Carpenter"),
    ("Carpentry Dept.", "Carpenter Shuttering"),
    ("Steel Fixing Dept.", "Foreman Steel Fixer"),
    ("Steel Fixing Dept.", "Chargehand Steel Fixer"),
    ("Steel Fixing Dept.", "Steel Fixer"),
    ("Labour Dept.", "Labour Charge Hand"),
    ("Labour Dept.", "Labour Foreman"),
    ("Labour Dept.", "Labourer +Helper +Imam"),
    ("Joinery Department", "Carpenter Bench"),
    ("Joinery Department", "Carpenter Finishing/Asst."),
    ("Joinery Department", "Electrician"),
    ("Joinery Department", "Carpenter Veneer"),
    ("Joinery Department", "Charge Hand Carp./Joinery / CNC / Finishing"),
    ("Joinery Department", "Foreman / Charge hand/ Polisher"),
    ("Joinery Department", "Foreman / Charge Hand /Machine operators"),
    ("Joinery Department", "Dispatch Worker"),
    ("Joinery Department", "Foreman Carpenter Finishing/Assembly"),
    ("Joinery Department", "Foreman Polisher"),
    ("Joinery Department", "Foreman Dispatching"),
    ("Joinery Department", "Foreman Joinery Finishing/Supervisor"),
    ("Joinery Department", "Foreman Painter /Charge Hand"),
    ("Joinery Department", "Charge Hand Labour"),
    ("Joinery Department", "Foreman Site"),
    ("Joinery Department", "Foreman Upholstery"),
    ("Joinery Department", "Foreman Veneer"),
    ("Joinery Department", "Operator Machines (Various)"),
    ("Joinery Department", "Painter Spray"),
    ("Joinery Department", "Painter Furniture"),
    ("Joinery Department", "Polisher Furniture"),
    ("Joinery Department", "Sander"),
    ("Joinery Department", "Supervisor Factory / Joinery"),
    ("Joinery Department", "Supervisor/site"),
    ("Joinery Department", "Tailor"),
    ("Joinery Department", "Upholster + Assistant"),
    ("Joinery Department", "Logistics Charge Hand"),
    ("Joinery Department", "Wood Curver"),
    ("Joinery Department", "Labour/Helper"),
    ("Aluminium Department", "Aluminium Fabricator/Asst."),
    ("Aluminium Department", "Dispatch Worker"),
    ("Aluminium Department", "Charge Hand Aluminium Fabricator"),
    ("Aluminium Department", "CNC programmer"),
    ("Aluminium Department", "Foreman Aluminium/Supervisor"),
    ("Aluminium Department", "Transport Incharge Factory/Logistic Charge Hand"),
    ("Aluminium Department", "Foreman factory Steel Div./ Foreman Steel"),
    ("Aluminium Department", "Foreman Site"),
    ("Aluminium Department", "Operator Machines / Forlift (Various) Charge Hand"),
    ("Aluminium Department", "Painter Spray / Charge hand"),
    ("Aluminium Department", "Steel fabricator"),
    ("Aluminium Department", "Charge Hand Steel Fabricator"),
    ("Aluminium Department", "Supervisor Maintenance"),
    ("Aluminium Department", "Supervisor site / Sr."),
    ("Aluminium Department", "Charge Hand Welder"),
    ("Aluminium Department", "Welder"),
    ("Aluminium Department", "Labour/Helper"),
    ("Marble & Tile Department (M & T)", "In Charge Marble Division"),
    ("Marble & Tile Department (M & T)", "Marble Coordinator/"),
    ("Marble & Tile Department (M & T)", "Operators / Charge Hand (Bridge, water Jet, etc)"),
    ("Marble & Tile Department (M & T)", "Marble Fabricator"),
    ("Marble & Tile Department (M & T)", "Marble Fabricator & Fixer"),
    ("Marble & Tile Department (M & T)", "Supervisor Production"),
    ("Marble & Tile Department (M & T)", "Foreman Marble / site"),
    ("Marble & Tile Department (M & T)", "Charge Hand Mason Marble"),
    ("Marble & Tile Department (M & T)", "Mason Marble"),
    ("Marble & Tile Department (M & T)", "Charge Hand Labour"),
    ("Marble & Tile Department (M & T)", "Labour/Helper"),
    ("Maintenance Department", "A/C Technician"),
    ("2", "Electrician Maintenance/Charge hand"),
    ("2", "Electrician Tools Mechanic/Tech. All Rounder/Asst."),
    ("2", "Foreman/ Asst. Machinery"),
    ("2", "Foreman Maintenance (Yard)"),
    ("2", "Supervisor Maintenance"),
    ("2", "Technician Maintenance/Helper"),
    ("A.I.R. Department (Ducting)", "Ductman"),
    ("A.I.R. Department (Ducting)", "DW Technicain"),
    ("A.I.R. Department (Ducting)", "HVAC Technician"),
    ("A.I.R. Department (Ducting)", "Plasma Operator"),
    ("A.I.R. Department (Ducting)", "Supervisor/Supervisor ducting/Administrator"),
    ("A.I.R. Department (Ducting)", "Technician"),
    ("A.I.R. Department (Ducting)", "Labour / Helper"),
    ("Water Tank Department", "Foreman Site"),
    ("Water Tank Department", "Technician WT"),
]
# WORKER_SEED: 156 entries

RESOURCE_SEED = [
    ("CONSTRUCTION DEPT.", "Chief Operating Offic /Proj Director"),
    ("PURCHASING DEPARTMENT", "Procurement & Purchasing Manager"),
    ("CONSTRUCTION DEPT.", "Manager / Project / Landscaping"),
    ("PURCHASING DEPARTMENT", "Purchasing Officer / Engineer"),
    ("CONSTRUCTION DEPT.", "Construction Managers"),
    ("PURCHASING DEPARTMENT", "Sales Supervisor"),
    ("CONSTRUCTION DEPT.", "Site /ProjectEngineers"),
    ("CONSTRUCTION DEPT.", "Material Engineer"),
    ("CONSTRUCTION DEPT.", "General Foremen/Supervisor"),
    ("ACCOUNTS DEPARTMENT", "Sr. Accountant"),
    ("ACCOUNTS DEPARTMENT", "Finance Manager"),
    ("CONSTRUCTION DEPT.", "Foremen Civil"),
    ("ACCOUNTS DEPARTMENT", "Accountant"),
    ("CONSTRUCTION DEPT.", "Charge Hands civil"),
    ("CONSTRUCTION DEPT.", "Land Surveyor/Assistants/Chainman"),
    ("CONSTRUCTION DEPT.", "Carpenter Shuttering"),
    ("ADMINISTRATION DEPARTMENT", "HR & Administration Manager"),
    ("CONSTRUCTION DEPT.", "Carpenter Finishing"),
    ("ADMINISTRATION DEPARTMENT", "Admin + HR + Officer + assistants"),
    ("CONSTRUCTION DEPT.", "Labour/Helper/Sand Blaster/Cleaner"),
    ("ADMINISTRATION DEPARTMENT", "Secretary/Receptionist"),
    ("CONSTRUCTION DEPT.", "Mason/ Block Plaster /Water Proof"),
    ("ADMINISTRATION DEPARTMENT", "PRO/PR Mang. + IT Manager + IT Eng."),
    ("CONSTRUCTION DEPT.", "Painters Building"),
    ("ADMINISTRATION DEPARTMENT", "Document Cont./ Assist/data entry+Custo"),
    ("CONSTRUCTION DEPT.", "Steel Fixers"),
    ("ADMINISTRATION DEPARTMENT", "Time Keepers + Asstt."),
    ("CONSTRUCTION DEPT.", "GRC / Gypsum Workers"),
    ("ADMINISTRATION DEPARTMENT", "Camps Incharge + Camp Boss + asstt."),
    ("CONSTRUCTION DEPT.", "Scaffolder"),
    ("CONSTRUCTION DEPT.", "Office Boy / Security Watchman"),
    ("PLANT DEPARTMENT", "Accountant/ Incharge/Purcahser/Log. Manager"),
    ("PLANT DEPARTMENT", "Logistic/Foreman /Ch. Hands"),
    ("PLANT DEPARTMENT", "workshop+ denter/Painter/Elect/Mechanic"),
    ("MEP DEPARTMENT", "MEP + Direcor + Manager"),
    ("PLANT DEPARTMENT", "Drivers/Operators/Pump oper /LD/HD/Tower Crane"),
    ("MEP DEPARTMENT", "Eng.+ Mech.+ Elect.+ MEP + Coordi."),
    ("PLANT DEPARTMENT", "Welder"),
    ("MEP DEPARTMENT", "MEP Foremen/Supervisor"),
    ("MEP DEPARTMENT", "MEP Charge Hands"),
    ("MEP DEPARTMENT", "Electrician + 02 IT support"),
    ("MEP DEPARTMENT", "Plumbers"),
    ("SAFETY & HEALTH DEPARTMENT", "HSE Manager"),
    ("MEP DEPARTMENT", "AC Ductmen + Technicians"),
    ("SAFETY & HEALTH DEPARTMENT", "HSE Advisor + Senior + Junior + Eng."),
    ("SAFETY & HEALTH DEPARTMENT", "HSE Inspectors/Asstt."),
    ("SAFETY & HEALTH DEPARTMENT", "Supervisor Lifting"),
    ("SAFETY & HEALTH DEPARTMENT", "Male Nurse/Security Guards + First Aider"),
    ("TECHNICAL DEPARTMENT", "Technical Director"),
    ("TECHNICAL DEPARTMENT", "Technical Manager"),
    ("TECHNICAL DEPARTMENT", "Technical / Struct. / Architect Engineers"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Operation Manager"),
    ("TECHNICAL DEPARTMENT", "Draftsman / Architects"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Manager+Steel+Project+ Factory+Coord."),
    ("TECHNICAL DEPARTMENT", "Fit-out Engineer"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Aluminium & Steel Fabricator"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Technicians, Welder, Painters"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Supervisor, Foremen & Ch. Hands"),
    ("PLANNING DEPARTMENT", "Planning Manager"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Machine operators"),
    ("PLANNING DEPARTMENT", "Planning Engineers"),
    ("ALUMINIUM AND METAL DEPARTMENT", "Labour + S.K. + TK + asst."),
    ("ALUMINIUM AND METAL DEPARTMENT", "Other Staff + office boy"),
    ("QA / QC DEPARTMENT", "QA / QC Manager / Sr."),
    ("QA / QC DEPARTMENT", "QA / QC Engineers / Senior"),
    ("JOINERY DEPARTMENT", "Operation Director/Manager/Coord."),
    ("QA / QC DEPARTMENT", "QA / QC Inspector/Lab. Tech."),
    ("JOINERY DEPARTMENT", "Supervisor + Foremen + Charge Hands"),
    ("QA / QC DEPARTMENT", "Close out / DLP Manager"),
    ("JOINERY DEPARTMENT", "Carp.furniture, Bench, Finishing, Veneer"),
    ("JOINERY DEPARTMENT", "Painter, Polisher and Sanders"),
    ("JOINERY DEPARTMENT", "Machine operators"),
    ("CONTRACT / QS DEPARTMENT", "Manager+ Director +Exective+Contracts"),
    ("JOINERY DEPARTMENT", "W.curver, Tailor, upholster, helpers"),
    ("CONTRACT / QS DEPARTMENT", "Estimator"),
    ("JOINERY DEPARTMENT", "Dispatch team & store/Time keeper + asstt."),
    ("CONTRACT / QS DEPARTMENT", "Quantity surveyor / Sr."),
    ("JOINERY DEPARTMENT", "Other Staff + office boy"),
    ("STORES DEPARTMENT (PIC)", "Stores Incharge/Store Supervisor"),
    ("Factory Maintenance Dept.", "Supervisor Machines Maintenance"),
    ("STORES DEPARTMENT (PIC)", "Store Keeper + Asstt."),
    ("Factory Maintenance Dept.", "Foreman Machinary + Maintenance"),
    ("Factory Maintenance Dept.", "A/C Technician"),
    ("Factory Maintenance Dept.", "Charge Hand Maintenance"),
    ("STORES DEPARTMENT (PIC)", "DUCT FACTORY"),
    ("Factory Maintenance Dept.", "Electrician Maintenance + Technician"),
    ("STORES DEPARTMENT (PIC)", "Supervisor"),
    ("Factory Maintenance Dept.", "Electrician Tools Mechanic"),
    ("STORES DEPARTMENT (PIC)", "Operator + Technicians"),
    ("STORES DEPARTMENT (PIC)", "Precast&Baching Plant"),
    ("STORES DEPARTMENT (PIC)", "Precast Director"),
    ("STORES DEPARTMENT (PIC)", "Erector"),
    ("Marble & Water Tank Department", "Incharge Marble Division/Asst."),
    ("STORES DEPARTMENT (PIC)", "Foreman"),
    ("Marble & Water Tank Department", "Marble Fabricator / Installer"),
    ("Marble & Water Tank Department", "Marble Machine Operators"),
    ("Marble & Water Tank Department", "Supervisor + Foremen + Charge Hands"),
    ("Marble & Water Tank Department", "Mason Marble"),
    ("Marble & Water Tank Department", "Mason Tile"),
    ("Marble & Water Tank Department", "Helper / Labour + office asstt."),
    ("Marble & Water Tank Department", "Foreman Water Tank Tech."),
    ("Marble & Water Tank Department", "GRAND TOTAL ALL DEPARTMENTS"),
]
# RESOURCE_SEED: 102 entries

