# Generated by Django 5.2.8 on 2026-04-09 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=50)),
                ('activity_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('planned_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Planned quantity (m2, m3, nos, etc.)', max_digits=12, null=True)),
                ('qty_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(help_text='Total bed count across all rooms')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Civil', 'Civil'), ('MEP', 'MEP'), ('Factory', 'Factory'), ('General', 'General')], default='General', max_length=20)),
                ('productivity_norms', models.JSONField(blank=True, help_text='e.g. {"units_per_hour": 5, "units_per_day": 40, "unit": "m2"}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='CampRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('bed_count', models.IntegerField(default=4)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hr_manpower.camp')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('camp', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='CampAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='e.g. "A1", "B2"', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Released', 'Released')], default='Active', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_allocations', to='attendance.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hr_manpower.camproom')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='attendance.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total working hours for the day', max_digits=5)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('csv', 'CSV Import')], default='manual', max_length=20)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cost_posted', models.BooleanField(default=False, help_text='True after labor cost has been posted to ActualCost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr_manpower.activity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_extension', to='attendance.attendance')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr_manpower.project')),
            ],
            options={
                'verbose_name': 'Attendance Extension',
            },
        ),
        migrations.CreateModel(
            name='ActualCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbs_code', models.CharField(help_text='CBS / cost center code for labor', max_length=100)),
                ('cost_date', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('basic_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('regular_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='hr_manpower.activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_costs', to='attendance.employee')),
                ('attendance_ext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual_cost', to='hr_manpower.attendanceextension')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_costs', to='hr_manpower.project')),
            ],
            options={
                'ordering': ['-cost_date'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hr_manpower.project'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allocation_percent', models.IntegerField(default=100, help_text='100 = full time, 50 = half time')),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Released', 'Released')], default='Planned', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='hr_manpower.activity')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='attendance.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_manpower.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.IntegerField(help_text='Number of workers required')),
                ('required_start_date', models.DateField()),
                ('required_end_date', models.DateField()),
                ('planned_man_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: qty × duration × hours/day', max_digits=12, null=True)),
                ('source', models.CharField(choices=[('planning', 'Planning (Auto)'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_demands', to='hr_manpower.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_demands', to='hr_manpower.project')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='hr_manpower.trade')),
            ],
            options={
                'ordering': ['required_start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('skill_level', models.CharField(blank=True, choices=[('Helper', 'Helper'), ('Skilled', 'Skilled'), ('Foreman', 'Foreman'), ('Supervisor', 'Supervisor')], max_length=20, null=True)),
                ('employment_type', models.CharField(choices=[('Direct', 'Direct'), ('Subcontract', 'Subcontract')], default='Direct', max_length=20)),
                ('basic_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily or hourly rate', max_digits=10, null=True)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='OT multiplier e.g. 1.5x', max_digits=4)),
                ('cost_center_default', models.CharField(blank=True, help_text='Default CBS / cost code for labor posting', max_length=100, null=True)),
                ('documents_dms_ids', models.JSONField(blank=True, help_text='Array of DMS document IDs: passport, visa, contract, training certs', null=True)),
                ('documents_valid', models.BooleanField(default=False, help_text='True only when all mandatory documents are uploaded and valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to='attendance.employee')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr_manpower.trade')),
            ],
            options={
                'verbose_name': 'Employee HR Profile',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='hr_manpower.trade'),
        ),
        migrations.CreateModel(
            name='ProductivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('man_hours_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Pulled from approved attendance for this activity on this date', max_digits=10)),
                ('quantity_executed', models.DecimalField(decimal_places=2, default=0.0, help_text='From QS / field entry', max_digits=12)),
                ('qty_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('productivity_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Auto-calculated: quantity_executed / man_hours_used', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_records', to='hr_manpower.activity')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_records', to='hr_manpower.project')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_records', to='hr_manpower.trade')),
            ],
            options={
                'ordering': ['-record_date'],
                'unique_together': {('project', 'activity', 'record_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'activity_code')},
        ),
    ]
