# Generated by Django 5.2.8 on 2025-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_department_site_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='slot',
            field=models.CharField(blank=True, choices=[('slot1', 'Slot 1 (9-11 AM)'), ('slot2', 'Slot 2 (11-1 PM)'), ('slot3', 'Slot 3 (2-4 PM)'), ('slot4', 'Slot 4 (4-6 PM)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date', 'slot')},
        ),
    ]
